### ISSUE TITLE
remove MAKER_PK

### ISSUE THREAD

**Issue by kimsk** [dexie-space/partial-cli-beta#3]
> There could be a MAKER_RECOVERY_PUZZLE that would be the standard puzzle of the maker. When 'recovering', accept puzzle reveal & solution in the partial coin solution and just return (a puzzle_reveal solution) - this will a) minimize the size of a normal (non-clawback) partial coin spend and b) allow for other recovery puzzles in the future (e.g., recovery from a vault/using secp). Will also get rid of the whole fee logic

**Comment by Yakuhito** [comment]
I thought about this a bit more - it adds flexibility, but it might actually increase cost a bit since you'll need to include the `sha256tree` function

**Comment by kimsk** [comment]
I like this idea because it provides flexibility in how we can clawback the offer. I will check how it affects the cost.
