### ISSUE TITLE
Use the pattern `(c COND_1 (c COND_2 (c COND_3 (if RECREATE_SELF RECREATE_COND ())))` instead of `filter-empty`

### ISSUE THREAD

**Issue by kimsk** [dexie-space/partial-cli-beta#6]
We used this pattern [before](https://github.com/dexie-space/partial-cli-beta/commit/08b5f7a58528bf696bba7827632859bda90cd706#diff-b67322d4578e501f328ecf747aa08c4e8141d7c47bb9f1b40afc1949edead626). I agree that this pattern looks better in our case.

**Comment by Yakuhito** [comment]
You could also do a simple `(list` of conditions and either:
 * prepend only the `CREATE_COIN` with `(c` (if there's a nice way to do it)
 * use `REMARK` when you don't want to re-create the coin
 * just create a 0-amount coin (although creating a coin adds ~1.200.000 cost, iirc)

**Comment by kimsk** [comment]
remove `filter-empty` and use `REMARK`, https://github.com/dexie-space/partial-cli-beta/pull/9
